#
# Makefile
# Clemens Ager, 2020-02-08 10:06
#

all: Jpsimumu.csv Jpsimumu2.csv

Jpsimumu.csv:
	curl "http://opendata.cern.ch/record/545/files/Jpsimumu.csv" -o "$@"

# following is a example for another data that is defined, but will never get used. 
Jpsimumu2.csv:
	curl "http://opendata.cern.ch/record/545/files/Jpsimumu.csv" -o "$@"

# vim:ft=make
#
