<<prepare data, include=FALSE>>=
library(ggplot2)
library(xtable)

load('work/transform.Rdata')
@

\section{example r code}

\subsection{a table}

There is a table.

<<a_table>>=
xtable(
	   with(trans.data, table(class, gender)),
	   caption="a pretty table of survival")
@

\subsection{a plot}

<<my_fig, fig.cap="a plot!!!">>=
ggplot(trans.data, mapping = aes(x=embarked, y=age, colour=survived)) +
	   geom_boxplot()
@

The plot is there at fig.\ref{fig:my_fig}.
